version: '3'
services:
  # chatsimple:
  #   image: chat/chat_simple:latest
  #   ports:
  #     - "9001:9001"
  #   depends_on:
  #     - db
  #     - redis
  #     - broker
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes: 
      - ./db/chat.sql/:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "3306:3306"
  redis: 
    image: redis:lastest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis
    restart: always
  namesrv:
    image: apache/rocketmq:5.0.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.0.0
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      NAMESRV_ADDR: namesrv:9876
    depends_on:
      - namesrv
    command: sh mqbroker -n namesrcv:9876 

volumes:
  redis-data: 

    