version: '3'
services:
  openresty:
    image: openresty/openresty
    volumes: 
      - ./openresty_nginx_conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports: 
      - "8001:80"
    depends_on:
      - chatsimple_1
      - chatsimple_2
      - chatsimple_3
  chatsimple_1:
    image: chat/chat_simple:1.0.0
    ports:
      - "9001:9001"
      - "7891:7891"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - CHAT_TAG_CURRENT=chat_a
      - MINIO_URL=http://minio:9000/
      - ROCKETMQ_NAME-SERVER=namesrv:9876
    depends_on:
      - db
      - redis
      - broker
      - minio
  chatsimple_2:
    image: chat/chat_simple:1.0.0
    ports:
      - "9002:9001"
      - "7892:7891"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - CHAT_TAG_CURRENT=chat_b
      - MINIO_URL=http://minio:9000/
      - ROCKETMQ_NAME-SERVER=namesrv:9876
    depends_on:
      - db
      - redis
      - broker
      - minio
  chatsimple_3:
    image: chat/chat_simple:1.0.0
    ports:
      - "9003:9001"
      - "7893:7891"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - CHAT_TAG_CURRENT=chat_c
      - MINIO_URL=http://minio:9000/
      - ROCKETMQ_NAME-SERVER=namesrv:9876
    depends_on:
      - db
      - redis
      - broker
      - minio
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: chat
    volumes: 
      - ./db/chat.sql/:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "3306:3306"
  redis: 
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
  namesrv:
    image: apache/rocketmq:5.0.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.0.0
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      NAMESRV_ADDR: namesrv:9876
    depends_on:
      - namesrv
    command: sh mqbroker -n namesrcv:9876 
  minio:
    image: minio/minio
    container_name: minio
    ports: 
      - 10000:9000
      - 10001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./data:/data
    command: server --console-address ':9001' /data
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  mc: # create minio bucket and set anouymous privilege
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/chat;
      /usr/bin/mc anonymous set download myminio/chat;
      exit 0;
      "

volumes:
  redis-data: 

    