version: '3'
services:
  openresty:
    image: openresty/openresty
    volumes: 
      - ./openresty_nginx_conf/nginx.conf:/home/docker/openresty/nginx/conf/nginx.conf
    ports: 
      - "8001:80"
    depends_on:
      - chatsimple_1
      - chatsimple_2
      - chatsimple_3
  chatsimple_1:
    image: chat/chat_simple:latest
    ports:
      - "9001:9001"
      - "7891:7891"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - ROCKETMQ_NAME-SERVER=namesrv:9876
    depends_on:
      - db
      - redis
      - broker
  chatsimple_2:
    image: chat/chat_simple:latest
    ports:
      - "9002:9002"
      - "7892:7892"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - ROCKETMQ_NAME-SERVER=namesrv:9876
    depends_on:
      - db
      - redis
      - broker
  chatsimple_3:
    image: chat/chat_simple:latest
    ports:
      - "9003:9003"
      - "7893:7893"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - ROCKETMQ_NAME-SERVER=namesrv:9876
    depends_on:
      - db
      - redis
      - broker
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes: 
      - ./db/chat.sql/:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "3306:3306"
  redis: 
    image: redis:lastest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis
    restart: always
  namesrv:
    image: apache/rocketmq:5.0.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.0.0
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      NAMESRV_ADDR: namesrv:9876
    depends_on:
      - namesrv
    command: sh mqbroker -n namesrcv:9876 

volumes:
  redis-data: 

    