spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # password: your-password # 如果有密码
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
  application:
    name: chat_simple
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: dr
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: async-producer-group
  consumer:
    group: async-consumer-group
    single: async-consumer-single
    composition: async-consumer-composition
mq:
  topic:
    multi-chat: muilt-chat
    single-chat: single-chat
    composition: composition

  
redisson:
  config: 
    singleServerConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      # password: ${spring.data.redis.password}
      subscriptionsPerConnection: 5
      clientName: ${spring.application.name}
      address: "redis://${spring.redis.data.host}:${spring.data.redis.port}"
      database: ${spring.redis.database}
      connectionPoolSize: 64      # 连接池大小
      connectionMinimumIdleSize: 24 # 最小空闲连接数
      subscriptionConnectionPoolSize: 50
# ws:
#   netty:
#     path: /chat

server: 
  port: 9001
chat:
  server:
    port: 7891